apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx-argo-application-new
  namespace: default
spec:
  project: default
 
  source:
    repoURL: https://github.com/YashnaHKanchan/jenkins-new.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-nginx
 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
 
    automated:
      selfHeal: true
      prune: true