apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-service-new
spec:
  selector:
    app: demo-nginx-new
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
   nodePort: 30010  
  type: NodePort